import type { IconType } from "react-icons";
import { FaAws, FaJava } from "react-icons/fa6";
import {
  SiAngular, SiBun, SiC, SiCplusplus, SiCss, SiDjango, SiDocker, SiEthereum, SiExpress,
  SiFigma, SiFirebase, SiFlutter, SiFramer, SiGit, SiGithub, SiGithubactions, SiGo,
  SiGraphql, SiHtml5, SiJavascript, SiJsonwebtokens, SiKubernetes, SiLinux, SiMongodb,
  SiMysql, SiNextdotjs, SiNginx, SiNodedotjs, SiPostgresql, SiPostman, SiPrisma, SiPython,
  SiReact, SiRedis, SiRedux, SiRust, SiSass, SiShadcnui, SiSocketdotio, SiSolidity,
  SiSupabase, SiSvelte, SiTailwindcss, SiThreedotjs, SiTypescript, SiVercel, SiVite,
  SiVuedotjs, SiFastapi, SiFlask, SiScikitlearn, SiTensorflow, SiKeras, SiPytorch, SiPandas,
  SiNumpy, SiStreamlit, SiJupyter, SiOpencv, SiHuggingface, SiMediapipe, SiPlotly,
  SiSqlalchemy, SiGooglecolab, SiRailway, SiChartdotjs,
} from "react-icons/si";

/**
 * Every icon that can be used in `techStack` (src/data/portfolio.ts).
 * `color` is the brand colour shown on hover. "fg" means "use the text colour"
 * (for black/white logos so they work in both light and dark mode).
 * Want another one? Find it at https://react-icons.github.io/react-icons and add a line.
 */
export const techIcons = {
  HTML: { icon: SiHtml5, color: "#E34F26" },
  CSS: { icon: SiCss, color: "#1572B6" },
  JavaScript: { icon: SiJavascript, color: "#F7DF1E" },
  TypeScript: { icon: SiTypescript, color: "#3178C6" },
  React: { icon: SiReact, color: "#61DAFB" },
  "Next.js": { icon: SiNextdotjs, color: "fg" },
  "Tailwind CSS": { icon: SiTailwindcss, color: "#06B6D4" },
  Sass: { icon: SiSass, color: "#CC6699" },
  "shadcn/ui": { icon: SiShadcnui, color: "fg" },
  "Framer Motion": { icon: SiFramer, color: "#0055FF" },
  Redux: { icon: SiRedux, color: "#764ABC" },
  Vite: { icon: SiVite, color: "#646CFF" },
  Vue: { icon: SiVuedotjs, color: "#4FC08D" },
  Angular: { icon: SiAngular, color: "#DD0031" },
  Svelte: { icon: SiSvelte, color: "#FF3E00" },
  "Three.js": { icon: SiThreedotjs, color: "fg" },
  Figma: { icon: SiFigma, color: "#F24E1E" },
  "Node.js": { icon: SiNodedotjs, color: "#5FA04E" },
  Express: { icon: SiExpress, color: "fg" },
  "Socket.io": { icon: SiSocketdotio, color: "fg" },
  GraphQL: { icon: SiGraphql, color: "#E10098" },
  JWT: { icon: SiJsonwebtokens, color: "fg" },
  Prisma: { icon: SiPrisma, color: "fg" },
  PostgreSQL: { icon: SiPostgresql, color: "#4169E1" },
  MongoDB: { icon: SiMongodb, color: "#47A248" },
  MySQL: { icon: SiMysql, color: "#4479A1" },
  Redis: { icon: SiRedis, color: "#FF4438" },
  Firebase: { icon: SiFirebase, color: "#FFCA28" },
  Supabase: { icon: SiSupabase, color: "#3FCF8E" },
  Docker: { icon: SiDocker, color: "#2496ED" },
  Kubernetes: { icon: SiKubernetes, color: "#326CE5" },
  AWS: { icon: FaAws, color: "#FF9900" },
  Vercel: { icon: SiVercel, color: "fg" },
  Nginx: { icon: SiNginx, color: "#009639" },
  Git: { icon: SiGit, color: "#F05032" },
  GitHub: { icon: SiGithub, color: "fg" },
  "GitHub Actions": { icon: SiGithubactions, color: "#2088FF" },
  Linux: { icon: SiLinux, color: "#FCC624" },
  Postman: { icon: SiPostman, color: "#FF6C37" },
  Java: { icon: FaJava, color: "#F89820" },
  Python: { icon: SiPython, color: "#3776AB" },
  "C++": { icon: SiCplusplus, color: "#00599C" },
  C: { icon: SiC, color: "#A8B9CC" },
  Go: { icon: SiGo, color: "#00ADD8" },
  Rust: { icon: SiRust, color: "fg" },
  Django: { icon: SiDjango, color: "#44B78B" },
  Flutter: { icon: SiFlutter, color: "#02569B" },
  Bun: { icon: SiBun, color: "fg" },
  Solidity: { icon: SiSolidity, color: "fg" },
  Ethereum: { icon: SiEthereum, color: "#8C8CFF" },
  // --- AI / ML & Python ---
  FastAPI: { icon: SiFastapi, color: "#009688" },
  Flask: { icon: SiFlask, color: "fg" },
  "scikit-learn": { icon: SiScikitlearn, color: "#F7931E" },
  TensorFlow: { icon: SiTensorflow, color: "#FF6F00" },
  Keras: { icon: SiKeras, color: "#D00000" },
  PyTorch: { icon: SiPytorch, color: "#EE4C2C" },
  pandas: { icon: SiPandas, color: "#E70488" },
  NumPy: { icon: SiNumpy, color: "#4DABCF" },
  Streamlit: { icon: SiStreamlit, color: "#FF4B4B" },
  Jupyter: { icon: SiJupyter, color: "#F37626" },
  OpenCV: { icon: SiOpencv, color: "#5C3EE8" },
  "Hugging Face": { icon: SiHuggingface, color: "#FFD21E" },
  MediaPipe: { icon: SiMediapipe, color: "#0097A7" },
  Plotly: { icon: SiPlotly, color: "#7A76FF" },
  SQLAlchemy: { icon: SiSqlalchemy, color: "#D71F00" },
  "Google Colab": { icon: SiGooglecolab, color: "#F9AB00" },
  "Chart.js": { icon: SiChartdotjs, color: "#FF6384" },
  Railway: { icon: SiRailway, color: "fg" },
} satisfies Record<string, { icon: IconType; color: string }>;

export type TechName = keyof typeof techIcons;
